### ISSUE TITLE
Delete local file after PutObject

### ISSUE THREAD

**Issue by yeahe83** [minio/minio-dotnet#697] opened 2022-10-04 11:51 UTC
Hi, I tried to delete the file after uploading, but it always causes an error, even if the upload was successful.
```
// Upload a file to bucket.
await minio.PutObjectAsync(bucketName, objectName, filePath, contentType);
Console.WriteLine("Successfully uploaded " + objectName);
File.Delete(filePath);
```
The process cannot access the file 'C:\111.txt' because it is being used by another process.

**Comment by ebozduman** [comment] 2022-10-07 09:19
@yeahe83 

It looks like a timing issue in your environment rather than it being a MinIO issue/bug. 

I still tried, but could not reproduce it on my setup (latest code, Ubuntu)

So, first let's make sure a couple of things in your setup:
- Make sure you run with the latest code
- Don't use the deprecated form of the api command. Although it does the same thing at this point, there is no guarantee it will behave the same way in the future. Also add the missing `.ConfigureAwait(false)` call when you `await` for the api, like:
```
            var putObjectArgs = new PutObjectArgs()
                .WithBucket(bucketName)
                .WithObject(objectName)
                .WithContentType(contentType)
                .WithFileName(filePath);
            await minio.PutObjectAsync(putObjectArgs).ConfigureAwait(false);
```

Give it a try using the above suggested changes in your setup.

If you still see the issue then consider trying one of the followings:
As async functions run asynchronously, there is a chance that you might be deleting the source file while your `PutObjectAsync()` is still holding it. That must be the reason for the "still being used by another process" error message.

You can try a couple of things:
- Instead of `await` use `Wait()` method, like: ~`await`~`minio.PutObjectAsync(putObjectArgs).Wait();`
or
- Add some delay before trying to delete your source file so that `PutObjectAsync()` has enough time to release it. You can call `Task.Delay(<time-in-milliseconds>)` after `PutObjectAsync()` call and before deleting the source file. 
Delay time would depend on your environment/OS etc.

Closing it since this is not a MinIO issue.
Please reopen it if you think otherwise.

**Closed by ebozduman** 2022-10-07 09:19 UTC
Labels: not our bug

**Comment by LaXiS96** [comment] 2023-01-18 15:35
I just had the same problem in a net6.0 project with version 4.0.7 of this library.
I am calling `System.IO.File.Move` just after a `PutObjectAsync.WithFileName`, but the move constantly fails for the same reason as OP, even with delays and continuously retrying.
The process that is blocking the file is the program itself (confirmed with PowerToys), which is also confirmed by the fact that commenting the `PutObjectAsync` "fixes" the problem.

I worked around the problem by manually handling the file stream:
```
using (var stream = new FileStream(@"C:\file.txt", FileMode.Open, FileAccess.Read))
{
    await _minioClient.PutObjectAsync(new PutObjectArgs()
        .WithBucket("bucket")
        .WithObject("file.txt")
        .WithStreamData(stream)
        .WithObjectSize(stream.Length)
        .WithContentType("application/octet-stream"));
}
```
This is identical to what the library is doing internally: https://github.com/minio/minio-dotnet/blob/afa9dad8e965a8762b33b05587f9d6398b3ad301/Minio/ApiEndpoints/ObjectOperations.cs#L621

There is obviously something that is interfering with the release of the file lock, I wouldn't dismiss the library that quickly @ebozduman ...

Just some thoughts for people who might stumble upon this issue in the future:
- do not replace `await` with `.Wait()`, that's like the worst thing you could do (see https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md)
- `ConfigureAwait(false)` will only make a difference if you are working with some kind of UI (WinForms, WPF, ...) or in .NET Framework
- adding a delay might work but it's not guaranteed, yet it will still slow your program down

**Comment by ebozduman** [comment] 2023-01-18 22:47
Thank you @LaXiS96 
I'll check it

**Comment by vadysa** [comment] 2023-12-14 11:09
Still an actual bug, it needs to be fixed
