### ISSUE TITLE
ListenBucketNotificationsAsync usage

### ISSUE THREAD

**Issue by DominikHerold** [minio/minio-dotnet#649] opened 2022-06-20 20:21 UTC
Hi,

I'm running locally a MinIO instance and implemented the `ListenBucketNotifications` like it is described [here](https://github.com/minio/minio-dotnet/blob/master/Minio.Examples/Cases/ListenBucketNotifications.cs)
I'm uploading a file via the MinIO console but the `onNext` Action does not kick in due to `onCompleted` is already executed. 
Actually `ListenBucketNotificationsAsync` is intended to get informed in case `EventType` is `EventType.ObjectCreatedAll`, isn't it?
Did I missed something or is there another way to get informed when a file is uploaded?
Thanks in advance.

**Comment by ebozduman** [comment] 2022-06-29 04:59
@DominikHerold 

I cannot reproduce the issue here with my local setup.
Could you please attach here the code you've seen the problem with?

**Comment by ebozduman** [comment] 2022-06-29 09:27
I reproduced the issue.
It turns out that this is just a simple timing issue as anticipated. So, subscriber needs some time to create notification for the event to be captured.
That is, if you add some sleep time after the event happens, then it will be captured and reported as expected.

Example:
```
using System.Threading;
                :
                :
                await _minio.PutObjectAsync(putObjectArgs);
                Console.WriteLine("Successfully uploaded");
                Thread.Sleep(350);
```

Please give it a try and let us know. You may close the issue if it works.

**Comment by ebozduman** [comment] 2022-07-04 04:37
@DominikHerold 

Did you have a chance to check it out?

**Comment by ebozduman** [comment] 2022-07-06 07:58
Closing...
Everything works as expected.

**Comment by codemnk** [comment] 2022-07-06 19:38
Having same issue. onCompleted is executed almost immediately after observable.Subscribe.
I am pretty sure the issue is in using of async void lambda in
https://github.com/minio/minio-dotnet/blob/f30de0606072b06d2553f8ec24efde4def631ad7/Minio/DataModel/BucketOperationsArgs.cs#L398

ResponseWriter is Action<Stream>. 
Basically response is disposed before stream is processed since calling code does not "await" on async void lambda.
https://devblogs.microsoft.com/pfxteam/potential-pitfalls-to-avoid-when-passing-around-async-lambdas/
https://www.jetbrains.com/help/resharper/AsyncVoidLambda.html

**Comment by ebozduman** [comment] 2022-07-08 08:19
Thank you @codemnk 
I'll check it out and fix the issue accordingly.

**Comment by ebozduman** [comment] 2022-07-19 00:28
@codemnk ,

To investigate the void async lambda function issue in our code and a possible for it, I first created a new wrapper function that encapsulates the response writer and calls and waits on it with `.Wait()`,
``` 
public void ProcessFunctionResponseWriter(Func<Stream, Task> func, Stream stream)
{
    func(stream).Wait();
}
```

and  added a new response writer, `FunctionResponseWriter`, without touching the existing definition `ResponseWriter`, so that the existing code is not touched, and hence any chance to cause regression problems are eliminated.
```
public Func<Stream, Task> FunctionResponseWriter { get; set; }
```

Then I called `ProcessFunctionResponseWriter` method exactly the same way it is done for `ResponseWriter`.
```
if (requestMessageBuilder.FunctionResponseWriter != null)
{
    requestMessageBuilder.ProcessFunctionResponseWriter(requestMessageBuilder.FunctionResponseWriter, responseResult.ContentStream);
}
```

However, when I run both old and the new code, I don’t see any behavior differences and when the execution stops prematurely.

So, I think the problem is not the void async lambda. The subscriber’s OnNext action is interrupted and the interrupt comes from the observable created by `Observable.Create`. 

After our team discussed the issue, the decision is that waiting for the subscriber rx action is the easiest solution or the workaround at this point.
This is just an example how to workaround the issue almost always:
```
subscription = observable.Subscribe(
    ev => 
    {
        Thread thread = new Thread( () => Notify(ev));
        thread.Start();
},
:
:
```

I’ll still be looking into this part of the code and logic to see what can be done.

Please don't hesitate to discuss. You are more than welcome to give us your opinion.

**Comment by ebozduman** [comment] 2022-07-20 10:16
Thanks to @codemnk  for providing a new scenario where void as lambda function may cause an issue for bucket notifications.
So, ,reopened this issue to refer it in the PR.

**Closed** 2022-07-20 17:09 UTC
Labels: priority: medium
