### ISSUE TITLE
Both spaces and pluses are serialized to pluses in the .NET SDK

### ISSUE THREAD

**Issue by sebastianbk** [minio/minio-dotnet#342] opened 2019-10-08 16:11 UTC
Hello,

I am making use of the Minio SDK for .NET together with the [Minio Gateway for GCS](https://docs.min.io/docs/minio-gateway-for-gcs.html) and, in the beginning, everything was working flawlessly. I really appreciate how easy it is to get started with and how well it generally works.

However, I have come across an issue that's causing quite a lot of trouble for me. When using the `ListObjectsAsync` method in the .NET SDK, I have noticed that both spaces and pluses are being serialized to pluses, making it impossible to know what the real file/folder name is.

As I already have thousands of buckets with all kinds of filenames in them, I really can't seem to figure out whether a plus is really a space or a plus. I checked in the Minio Browser and, there, there is no issue. It distinguishes nicely between my files with spaces and pluses in them, respectively.

Is this a bug in the SDK or a result of communicating with the Minio Gateway over HTTP where spaces can sometimes be serialized as pluses?

I would very much like to offer my help in solving this issue, as I would love to make use of Minio but can't right now.

**Comment by harshavardhana** [comment] 2019-10-08 16:26
Yes we need to fix this.. Thanks for reporting @sebastianbk

**Comment by vadmeste** [comment] 2019-10-08 17:03
> Yes we need to fix this.. Thanks for reporting @sebastianbk

The issue should be fixed after releasing minio-go and updating it in minio/minio. I am happy to test gateway S3 & Azure to be sure.

**Comment by harshavardhana** [comment] 2019-10-08 17:12
Here it's gcs gateway - I think the issue is in dotnet SDK

**Comment by vadmeste** [comment] 2019-10-08 17:15
> Here it's gcs gateway - I think the issue is in dotnet SDK

My bad, yes.. GCS gateway doesn't use minio-go

**Comment by sebastianbk** [comment] 2019-10-08 20:33
Wauw, thanks for the fast response on this issue. Your commitment is really inspiring!

Would you be able to offer a timeline for when the fix could be released?

**Comment by harshavardhana** [comment] 2019-10-08 21:06
No timeline @sebastianbk but soon.

**Comment by sebastianbk** [comment] 2019-10-10 12:59
Let me know when you'll release this. I am desperate to make use of it! 😃

**Closed** 2019-10-11 00:14 UTC
Labels: community, priority: medium
