### ISSUE TITLE
WithSSL(false) is ignored with MinioClientFactory

### ISSUE THREAD

**Issue by fabientrissie** [minio/minio-dotnet#878] opened 2023-10-06 14:52 UTC
Hi, I think there is an issue when we want to inject a Minio client without using SSL.

Here's my code in my program.cs

builder.Services.AddMinio(client =>
{
    client.WithEndpoint(endpoint)
                              .WithCredentials(accessKey, secretKey)
                              .WithSSL(false)
                              .Build();
});

But the client always have secure to True in my service classes.

I check the source code and I can this in "MinioClientFactory.cs" line 40 this code, and I think my configuration is ignored because of that :

var client = new MinioClient()
            .WithSSL();

configureClient(client);

Thanks for your help

**Comment by S3V3N-11** [comment] 2023-10-07 16:38
Hey, I have the same problem.

`Program.cs`
![image](https://github.com/minio/minio-dotnet/assets/7726926/e2350ef9-bfdd-45f4-8b5c-956c7812fbd5)

Injected MinioClient
![image](https://github.com/minio/minio-dotnet/assets/7726926/84131dce-972a-4032-813e-0417e8adb6f9)

**Comment by ebozduman** [comment] 2023-10-21 05:48
Duplicate of #884 
This issue is addressed in PR #844
Closing...

**Closed by ebozduman** 2023-10-21 05:48 UTC

**Comment by forever84721** [comment] 2023-10-30 16:57
The problem with WithSSL(false) seems still same. 
Is it because the new version has not been released to nuget yet?
I see that nuget is still version 6.0.0 on 2023/9/30

**Comment by ebozduman** [comment] 2023-11-01 16:11
Yes, @forever84721 
We haven't generated a new nuget package yet.
Please try it out the master branch from the top of the minio-dotnet repo.
