### ISSUE TITLE
Bucket Notifications for Kafka, doesn't have metadata information in the event message

### ISSUE THREAD

**Issue by vikhar** [minio/minio-dotnet#309] opened 2019-06-04 10:33 UTC
We are using .Net client to upload object to a bucket in minio and listening the events at Kafka end point.

We can successfuly upload the files and receive events in kafka, howevr we are not receiving the metadata information in kafka event message, which we are passing in PutObjectAsync method.

Below is the .Net code sample to upload the files and corresponding event message we receive at Kafka. If you see the userMetadata key in Kafka message doesnt have the values which we inserted via .Net Code

**C# Code Sample:**

                var url = minio.PresignedGetObjectAsync(bucketName, objectName, 14400).GetAwaiter().GetResult();
                var metaData = new Dictionary<string, string>();
                metaData.Add("Name", "TestUploader");
                metaData.Add("targetId", url);
                minio.PutObjectAsync(bucketName, objectName, filePath, contentType, metaData).GetAwaiter().GetResult();

**Kafka Message:**
{"EventName":"s3:ObjectCreated:Put","Key":"testbuckevivek/TestData8.zip","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2019-06-04T09:34:26Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"Q39BJ7AEIUM7B2EUVVBM"},"requestParameters":{"accessKey":"Q39BJ7AEIUM7B2EUVVBM","region":"","sourceIPAddress":"<IPADDRESS>"},"responseElements":{"x-amz-request-id":"15A4F51ADFE4E4C8","x-minio-deployment-id":"f2534abf-b105-47e1-9e4c-b2c195575df2","x-minio-origin-endpoint":"http://<IPADDRESS>:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"testbuckevivek","ownerIdentity":{"principalId":"Q39BJ7AEIUM7B2EUVVBM"},"arn":"arn:aws:s3:::testbuckevivek"},"object":{"key":"TestData8.zip","size":52825,"eTag":"5979052cb3d14599fd994662308d865f-1","contentType":"application/zip","userMetadata":{"content-type":"application/zip"},"versionId":"1","sequencer":"15A4F51AE8EC0344"}},"source":{"host":"192.168.43.117","port":"","userAgent":"MinIO (Microsoft Windows NT 6.2.9200.0;x86_64) minio-dotnet/1.0.9"}}]}

**Comment by kannappanr** [comment] 2019-06-04 13:49
Does the metadata get stored in `MinIO`, if yes, then I think this issue belongs in `minio/minio` repo. You can verify that by using `mc stat myminio/bucketname/object`, where `myminio` is the alias, `bucketname` is the name of the bucket and `object` is the object name. Can you also provide the `MinIO` version and the command you used to start `MinIO`?

**Comment by vikhar** [comment] 2019-06-04 15:24
When I am doing mc stat command, it says "Unable to stat `play/testbuckevivek/TestData9.zip`. Target `play/testbuckevivek/TestData9.zip` not found."

However I ensure that the object is there by manually looking at the browser and using mc ls command as well.

![image](https://user-images.githubusercontent.com/17875934/58891805-cff6ee00-870a-11e9-9322-f50fb74d3d6f.png)

Version: I am using **.net Framework 4.6.2** and **Minio version is: 3.0.10** to upload the objects.

**Comment by Praveenrajmani** [comment] 2019-06-04 16:17
> Does the metadata get stored in `MinIO`, if yes, then I think this issue belongs in `minio/minio` repo. You can verify that by using `mc stat myminio/bucketname/object`, where `myminio` is the alias, `bucketname` is the name of the bucket and `object` is the object name. Can you also provide the `MinIO` version and the command you used to start `MinIO`?

@kannappanr No it is not a MinIO issue. It was working with minio-py

**Comment by vikhar** [comment] 2019-06-05 05:39
Hi @kannappanr @Praveenrajmani  Can we have a quick working session, to ensure I am not using anything wrongly and it indeed is an issue. This will give overall clarity as well on where the issue is actually.

**Comment by harshavardhana** [comment] 2019-06-05 06:22
>     var url = minio.PresignedGetObjectAsync(bucketName, objectName, 14400).GetAwaiter().GetResult();
>             var metaData = new Dictionary<string, string>();
>             metaData.Add("Name", "TestUploader");
>             metaData.Add("targetId", url);
>             minio.PutObjectAsync(bucketName, objectName, filePath, contentType, metaData).GetAwaiter().GetResult();

The problem is in the library is not doing a correct job at handling metadata, it is expecting that as a user you should add "X-Amz-Meta" as part of the key name when providing metadata. Instead of adding it proactively which other libraries already do. 

So as a workaround @vikhar you can simply do the following modification and it will work. 

```csharp
            var url = minio.PresignedGetObjectAsync(bucketName, objectName, 14400).GetAwaiter().GetResult();
            var metaData = new Dictionary<string, string>();
            metaData.Add("X-Amz-Meta-Name", "TestUploader");
            metaData.Add("X-Amz-Meta-targetid", url);
            minio.PutObjectAsync(bucketName, objectName, filePath, contentType, metaData).GetAwaiter().GetResult();
```

This is indeed a bug in the library we should fix.

**Comment by vikhar** [comment] 2019-06-05 06:54
Cool, let me try that.

**Comment by vikhar** [comment] 2019-06-05 09:20
@harshavardhana It worked, I am moving ahead with this workaround for now, please let me know once the actual issue is fixed.
Thanks

**Comment by kannappanr** [comment] 2019-07-26 22:31
ping @Praveenrajmani

**Comment by kannappanr** [comment] 2019-12-12 14:55
closing this issue as https://github.com/minio/minio-dotnet/pull/356 has been merged

**Closed by kannappanr** 2019-12-12 14:55 UTC
Labels: community, priority: medium
