### ISSUE TITLE
Error in .net 4.8 WebApplications Could not load file or assembly 'Minio'

### ISSUE THREAD

**Issue by yuri153** [minio/minio-dotnet#712] opened 2022-11-09 02:30 UTC
An error ocurre when start WebApplications in .net 4.8, in version 4.0.0 of this nuget, this error not ocurre

![image](https://user-images.githubusercontent.com/37423573/200722496-9b131762-91db-495c-8da1-731bca73eec4.png)

**Comment by ebozduman** [comment] 2022-11-15 09:52
@yuri153,

Please check the following link:
https://stackoverflow.com/questions/20212035/how-to-fix-could-not-load-file-or-assembly-xxx-or-one-of-its-dependencies-st

You'll see there are a considerable number of different cases with different fixes, even some talk about VisualStudio settings.
So, we believe this issue is not related to MinIO, hence closing the issue at this point.
But, please feel free to reopen and update the issue with your findings, and reasoning if you disagree.

**Closed by ebozduman** 2022-11-15 09:52 UTC
Labels: working as intended

**Comment by yuri153** [comment] 2022-11-16 01:41
@ebozduman 

I tried some differents fixes, but unssuccessfully, I created a new project from zero and when I install the Minio version 4.0.0 works fine, but when I try versions 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5 and 4.0.6 doesn't work, I saw that in the version 4.0.0 have the .net framework 4.6, after this version I saw just .net 5, .net6 and .net standard, maybe this is related to the error

**Comment by ebozduman** [comment] 2022-11-19 08:30
Thanks @yuri153 

I forgot to mention we had a similar issue before, #643, and it was fixed on our side by removing one of the 2 references/versions of the same dependent assembly, `Newtonsoft.Json`, we had in `Minio.Functional.Tests.csproj` and `Minio.csproj` project files.

There is still an outstanding issue, #661, and it would have been better if I closed this issue as a duplicate of it.

Anyways, after digging and searching more, I found the following visual studio msbuild errors link:
https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3277?view=vs-2022

The problem is explained in the above link as:
```
MSB3277: Found conflicts between different versions of 'assembly' that could not be resolved
This error occurs during a build when more than one version of the same dependent assembly
 is referenced in a build of the same project.
:
:
The Global Assembly Cache (GAC) might also be a source of a potential conflict, in cases
where you are referencing a specific version of an assembly, but the GAC overrides it. 
https://learn.microsoft.com/en-us/dotnet/framework/app-domains/gac
```

Could you try the following possible resolutions, which worked for some:

1. Open your project or solution in Visual Studio, and select Tools > NuGet Package Manager > Package Manager Console.
    a. If you already have the `Microsoft.AspNet.Web.Optimization` package,
        then uninstall it and run the next command to reinstall it.
    b. Run `Install-Package Microsoft.AspNet.Web.Optimization` and check if it helps. 
2. Right click on your main project in VS and select the `Project Dependencies...`
    option and check the build order. Changes to the build sequence can
    be made here by correctly setting these dependencies. If this works for
    you, we can use `binding redirects` to fix it, at least for some cases.
3. Cleanup your GAC and remove old MinIO references. I think you need to use `gcutils -u <pkg-name>`. But be careful removing references from GAC as it could be dangerous for other libraries. 

Let's keep communicating about this issue in #661 going forward.
