### ISSUE TITLE
XML Not Well-Formed when setting bucket life cycle

### ISSUE THREAD

**Issue by rhuebnerNNI** [minio/minio-dotnet#782] opened 2023-05-11 12:19 UTC
When I try to set a bucket's life cycle I am first getting the life cycle of an existing bucket, once I get this life cycle I am trying to use the configuration from the existing bucket to set the life cycle of a different bucket. Both buckets exist, but I am getting the following errors.

Exception: 
`Minio.Exceptions.UnexpectedMinioException: 'MinIO API responded with message=The XML you provided was not well-formed or did not validate against our published schema'`

Call Stack: 
`This exception was originally thrown at this call stack:
    Minio.MinioClient.ParseErrorFromContent(Minio.ResponseResult) in MinioClient.cs
    Minio.MinioClient.ParseError(Minio.ResponseResult) in MinioClient.cs
    Minio.MinioClient..ctor.AnonymousMethod__94_0(Minio.ResponseResult) in MinioClient.cs
    Minio.MinioClient.HandleIfErrorResponse(Minio.ResponseResult, System.Collections.Generic.IEnumerable<Minio.ApiResponseErrorHandlingDelegate>, System.DateTime) in MinioClient.cs
    Minio.MinioClient.ExecuteTaskCoreAsync(System.Collections.Generic.IEnumerable<Minio.ApiResponseErrorHandlingDelegate>, Minio.HttpRequestMessageBuilder, bool, System.Threading.CancellationToken) in MinioClient.cs
    Minio.MinioClient.SetBucketLifecycleAsync(Minio.SetBucketLifecycleArgs, System.Threading.CancellationToken) in BucketOperations.cs
    NNIAPI.Models.DocumentManagement.ObjectStorage.EnsureBucketExists(Minio.MinioClient, string) in ObjectStorage.cs`

MinIO Console Log Details:
`API: PutBucketLifecycle
Time: 12:16:10 UTC 05/11/2023
DeploymentID: c721f7ef-a682-43f8-a893-0d08705773a6
RequestID: 175E15E1F7B31661
RemoteHost: 192.168.2.134
UserAgent: MinIO (Microsoft Windows 10.0.22621 ;X64) minio-dotnet/5.0.0.0
Error: The XML you provided was not well-formed or did not validate against our published schema (lifecycle.Error)

Backtrace: 
0: internal/logger/logger.go:258:logger.LogIf()
1: cmd/api-errors.go:2282:cmd.toAPIErrorCode()
2: cmd/api-errors.go:2307:cmd.toAPIError()
3: cmd/bucket-lifecycle-handlers.go:78:cmd.objectAPIHandlers.PutBucketLifecycleHandler()
4: net/http/server.go:2122:http.HandlerFunc.ServeHTTP()`

Code:
`Minio.GetBucketLifecycleArgs getBucketLifecycleArgs = new Minio.GetBucketLifecycleArgs()
                    .WithBucket("lifecycle-template");

                    Minio.DataModel.ILM.LifecycleConfiguration lfc = await client.GetBucketLifecycleAsync(getBucketLifecycleArgs).ConfigureAwait(false);

                    //Finally, set the life cycle of the bucket
                    Minio.SetBucketLifecycleArgs setBucketLifecycleArgs = new Minio.SetBucketLifecycleArgs()
                        .WithBucket(bucketName)
                        .WithLifecycleConfiguration(lfc);

                    await client.SetBucketLifecycleAsync(setBucketLifecycleArgs).ConfigureAwait(false);`

**Comment by Leprox43** [comment] 2023-08-11 13:27
Hi, i have the same problem in rules with Tags inside RuleFilter object.

A much simpler rule like this works
```cshap
new LifecycleRule()
{
    ID = "rule2",
    Expiration = new Expiration
    {
        Days = 15,
    },
    Filter = new RuleFilter()
    {
        Prefix = string.Empty
    },
    Status = LifecycleRule.LifecycleRuleStatusEnabled,
}
```

I'm trying to figure out how is not working, comparing the generate body in the api call with other language minio libraries

**Comment by yilezhu** [comment] 2023-08-24 08:23
The same error occurred in the old version of MinIO(2021-03-01), but there is no problem with the new version(2023-06-02).
`if (minio is null) throw new ArgumentNullException(nameof(minio));

            if (lfc == null)
            {
                lfc = new LifecycleConfiguration();
                lfc.Rules = new List<LifecycleRule>();
                lfc.Rules.Add(new LifecycleRule
                {
                    Expiration = new Minio.DataModel.Expiration() { Days=1},
                    Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED
                });

            }
            try
            {
                Console.WriteLine("Running example for API: SetBucketLifecycle");
                await minio.SetBucketLifecycleAsync(
                    new SetBucketLifecycleArgs()
                        .WithBucket(bucketName)
                        .WithLifecycleConfiguration(lfc)
                ).ConfigureAwait(false);
                Console.WriteLine($"Bucket Lifecycle set for bucket {bucketName}.");`

**Comment by rhuebnerNNI** [comment] 2023-08-24 12:33
> The same error occurred in the old version of MinIO(2021-03-01), but there is no problem with the new version(2023-06-02). `if (minio is null) throw new ArgumentNullException(nameof(minio));
> 
> ```
>         if (lfc == null)
>         {
>             lfc = new LifecycleConfiguration();
>             lfc.Rules = new List<LifecycleRule>();
>             lfc.Rules.Add(new LifecycleRule
>             {
>                 Expiration = new Minio.DataModel.Expiration() { Days=1},
>                 Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED
>             });
> 
>         }
>         try
>         {
>             Console.WriteLine("Running example for API: SetBucketLifecycle");
>             await minio.SetBucketLifecycleAsync(
>                 new SetBucketLifecycleArgs()
>                     .WithBucket(bucketName)
>                     .WithLifecycleConfiguration(lfc)
>             ).ConfigureAwait(false);
>             Console.WriteLine($"Bucket Lifecycle set for bucket {bucketName}.");`
> ```

Your code works for updating the LifeCycle rule, however, if you add a Filter object to your code you get the same error.
I added a Filter object to your code for creating the rule and get the same error, "XML Not Well-Formed"

`Minio.DataModel.ILM.LifecycleConfiguration lfc = new Minio.DataModel.ILM.LifecycleConfiguration();

lfc.Rules = new System.Collections.ObjectModel.Collection<LifecycleRule>();

lfc.Rules.Add(new LifecycleRule
{
    Expiration = new Minio.DataModel.Expiration() { Days = 30 },
    Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED,
    Filter = new Minio.DataModel.ILM.RuleFilter()
    {
        TheAndOperator = new Minio.DataModel.ILM.AndOperator()
        {
            Tags = new System.Collections.ObjectModel.Collection<Minio.DataModel.Tags.Tag>()
                    {
                        new Minio.DataModel.Tags.Tag(){ Key = recycleTagKey, Value = recycleTagValue }
                    }
        }
    }
});

//Finally, set the life cycle of the bucket
Minio.SetBucketLifecycleArgs setBucketLifecycleArgs = new Minio.SetBucketLifecycleArgs()
    .WithBucket(bucketName)
    .WithLifecycleConfiguration(lfc);

await client.SetBucketLifecycleAsync(setBucketLifecycleArgs).ConfigureAwait(false);`

**Comment by yilezhu** [comment] 2023-08-25 02:26
> > 老版本MinIO(2021-03-01)也出现同样的错误，但新版本(2023-06-02)没有问题。`if (minio 为 null) throw new ArgumentNullException(nameof(minio));
> > ```
> >         if (lfc == null)
> >         {
> >             lfc = new LifecycleConfiguration();
> >             lfc.Rules = new List<LifecycleRule>();
> >             lfc.Rules.Add(new LifecycleRule
> >             {
> >                 Expiration = new Minio.DataModel.Expiration() { Days=1},
> >                 Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED
> >             });
> > 
> >         }
> >         try
> >         {
> >             Console.WriteLine("Running example for API: SetBucketLifecycle");
> >             await minio.SetBucketLifecycleAsync(
> >                 new SetBucketLifecycleArgs()
> >                     .WithBucket(bucketName)
> >                     .WithLifecycleConfiguration(lfc)
> >             ).ConfigureAwait(false);
> >             Console.WriteLine($"Bucket Lifecycle set for bucket {bucketName}.");`
> > ```
> 
> 您的代码适用于更新 LifeCycle 规则，但是，如果您将 Filter 对象添加到代码中，则会出现相同的错误。 我在代码中添加了一个 Filter 对象来创建规则，但得到了相同的错误“XML Not Well-Formed”
> 
> ```
> Minio.DataModel.ILM.LifecycleConfiguration lfc = new Minio.DataModel.ILM.LifecycleConfiguration();
> 
> lfc.Rules = new System.Collections.ObjectModel.Collection<LifecycleRule>();
> 
> lfc.Rules.Add(new LifecycleRule
> {
>     Expiration = new Minio.DataModel.Expiration() { Days = 30 },
>     Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED,
>     Filter = new Minio.DataModel.ILM.RuleFilter()
>     {
>         TheAndOperator = new Minio.DataModel.ILM.AndOperator()
>         {
>             Tags = new System.Collections.ObjectModel.Collection<Minio.DataModel.Tags.Tag>()
>                     {
>                         new Minio.DataModel.Tags.Tag(){ Key = recycleTagKey, Value = recycleTagValue }
>                     }
>         }
>     }
> });
> 
> //Finally, set the life cycle of the bucket
> Minio.SetBucketLifecycleArgs setBucketLifecycleArgs = new Minio.SetBucketLifecycleArgs()
>     .WithBucket(bucketName)
>     .WithLifecycleConfiguration(lfc);
> 
> await client.SetBucketLifecycleAsync(setBucketLifecycleArgs).ConfigureAwait(false);
> ```

You try to upgrade the version of MinIO. I found that the version after May 4, 2022 only supports the setting of Day.

**Comment by yilezhu** [comment] 2023-08-25 02:27
@rhuebnerNNI You can try to upgrade the version of MinIO. I found that the version after May 4, 2022 only supports the setting of Day.

**Comment by Leprox43** [comment] 2023-08-25 07:19
@yilezhu i'm using this docker image of MinIO "minio/minio:RELEASE.2023-08-16T20-17-30Z" and i still have the issue with a lifecycle rule with tags

**Comment by yilezhu** [comment] 2023-08-25 07:24
> @yilezhu i'm using this docker image of MinIO "minio/minio:RELEASE.2023-08-16T20-17-30Z" and i still have the issue with a lifecycle rule with tags
can you show the code.

if (minio is null) throw new ArgumentNullException(nameof(minio));
        if (lfc == null)
        {
            lfc = new LifecycleConfiguration();
            lfc.Rules = new List<LifecycleRule>();
            lfc.Rules.Add(new LifecycleRule
            {
                Expiration = new Minio.DataModel.Expiration() { Days=1},
                Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED
            });

        }
        try
        {
            Console.WriteLine("Running example for API: SetBucketLifecycle");
            await minio.SetBucketLifecycleAsync(
                new SetBucketLifecycleArgs()
                    .WithBucket(bucketName)
                    .WithLifecycleConfiguration(lfc)
            ).ConfigureAwait(false);
            Console.WriteLine($"Bucket Lifecycle set for bucket {bucketName}.");

**Comment by Leprox43** [comment] 2023-08-25 15:34
I managed to figure out the problem with the LifecycleConfiguration with Tags, thanks to a co-worker who knows python.
These are the internal xml that the two libraries (.net and python) send respectively to MinIO:

_minio-dotnet_
```xml
<LifecycleConfiguration>
  <Rule>
    <ID>rule1</ID>
    <Expiration>
      <Days>7</Days>
    </Expiration>
    <Filter>
      <And>
        <Tag>
          <Key>k1</Key>
          <Value>v1</Value>
        </Tag>
        <Tag>
          <Key>k2</Key>
          <Value>v2</Value>
        </Tag>
      </And>
    </Filter>
    <Status>Enabled</Status>
  </Rule>
</LifecycleConfiguration>
```

_minio-python_
```xml
<LifecycleConfiguration>
  <Rule>
    <ID>rule1</ID>
    <Expiration>
      <Days>7</Days>
    </Expiration>
    <Filter>
      <And>
        <Prefix/>
        <Tag>
          <Key>k1</Key>
          <Value>v1</Value>
        </Tag>
        <Tag>
          <Key>k2</Key>
          <Value>v2</Value>
        </Tag>
      </And>
    </Filter>
    <Status>Enabled</Status>
  </Rule>
</LifecycleConfiguration>
```

minio-dotnet DON'T generate the xml node "<Prefix/>" inside the <And> node.
I also try to set prefix with a value not equals to string.Empty or null, but the output xml doesn't change

This is how i set a LifecycleConfiguration in C#
```cs
var lfc = new LifecycleConfiguration(new List<LifecycleRule>()
{
    new LifecycleRule()
    {
        ID = "rule1",
        Expiration = new Expiration
        {
            Days = 7,
        },
        Filter = new RuleFilter()
        {
            TheAndOperator = new AndOperator(prefix: null, new List<Tag>
            {
                new Tag("k1", "v1"),
                new Tag("k2", "v2"),
            }),
        },
        Status = LifecycleRule.LifecycleRuleStatusEnabled,
    }
});
```

**Comment by rhuebnerNNI** [comment] 2023-08-25 20:45
I tried your suggestions and unfortunately, this didn't fix the issue for me.

```
Minio.DataModel.ILM.LifecycleConfiguration lfc = new Minio.DataModel.ILM.LifecycleConfiguration(new List<Minio.DataModel.ILM.LifecycleRule>()
                    {
                        new Minio.DataModel.ILM.LifecycleRule()
                        {
                            ID = "DeletedRule",
                            Expiration = new Minio.DataModel.Expiration
                            {
                                Days = 30,
                            },
                            Filter = new Minio.DataModel.ILM.RuleFilter()
                            {
                                TheAndOperator = new Minio.DataModel.ILM.AndOperator(prefix: "", // or string.Empty in my case
                                new List<Minio.DataModel.Tags.Tag>
                                {
                                    new Minio.DataModel.Tags.Tag(){ Key = recycleTagKey, Value = recycleTagValue }
                                }),
                            },
                            Status = Minio.DataModel.ILM.LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED,
                        }
                    });

                    //Finally, set the life cycle of the bucket
                    Minio.SetBucketLifecycleArgs setBucketLifecycleArgs = new Minio.SetBucketLifecycleArgs()
                        .WithBucket(bucketName)
                        .WithLifecycleConfiguration(lfc);

                    await client.SetBucketLifecycleAsync(setBucketLifecycleArgs).ConfigureAwait(false);
```

**Comment by Leprox43** [comment] 2023-08-25 22:09
Sorry @rhuebnerNNI, maybe i didn't explain well: the problem is inside the library.

The proprety Prefix inside AndOperator class is wrongly marked as "internal" instead of "public".

Tomorrow i try to open a PR to fix it and praying that will approved asap 😅.

**Comment by Leprox43** [comment] 2023-08-26 14:38
I open a PR #853 😊

**Comment by ebozduman** [comment] 2023-09-16 20:21
The release is on hold.
I think it will happen in a couple of (business) days+-.

**Comment by leprox43** [comment] 2023-10-02 14:51
@rhuebnerNNI if you update the NuGet package to the last version (>= 6.0.0) the bug is resolved and you can close the issue 😄

**Closed** 2023-10-02 15:20 UTC
