### ISSUE TITLE
Setup interfaces for Minio Client to be testable

### ISSUE THREAD

**Issue by Disturbing** [minio/minio-dotnet#182] opened 2017-11-01 09:34 UTC
Would be great for the MinioClient to be testable via interfaces :)

**Comment by harshavardhana** [comment] 2017-11-01 21:36
Can you explain more on this a bit? Looks like the issue description is incomplete.

**Comment by Disturbing** [comment] 2017-11-13 01:19
I can't easily mock the MinioClient for testing - have to create a wrapper
around it.  Would be great to have the classes implement an interface.

**Comment by harshavardhana** [comment] 2017-11-13 02:49
An interface is only useful here if you wish to create many types of clients. That is out of scope for minio-dotnet IMHO.

**Comment by Disturbing** [comment] 2017-11-13 03:24
The point is if I want to make a Mock Minio folder (locally for testing), I
have to create some sort of Interface like

class IFileStorage
void GetFile(string path);

Within that I would have an implementation of minio.

Preferably, it would be nice to have IMinioClient, mock it, and return the
files as peer Minio's functions.

It's just a bit more test friendly is all, but not a priority.

Thanks for taking the time to consider.

**Closed** 2017-11-16 18:45 UTC
Labels: priority: medium, wontfix

**Comment by Roll4D6** [comment] 2019-07-07 11:16
Why the issue is closed? I think it makes sense to extract an interface from the MinioClient. As @Disturbing said it would make easier to mock MinioClient and easier for dependency injection
