### ISSUE TITLE
 WithStreamData PutObjectAsync exception

### ISSUE THREAD

**Issue by hvppy** [minio/minio-dotnet#670] opened 2022-07-30 16:38 UTC
var args = new PutObjectArgs().WithBucket(buckName).WithObject(objectName).WithStreamData(stream).WithObjectSize(stream.Length);
await minio.PutObjectAsync(args);

is exception:
One or more errors occurred. (Object reference not set to an instance of an object.)

 ---------------
var args = new PutObjectArgs().WithBucket(buckName).WithObject(objectName).WithFileName(filefullname).WithObjectSize(stream.Length).WithContentType("application/octet-stream");
await minio.PutObjectAsync(args);

is ok

**Comment by vuhuy** [comment] 2022-08-17 15:32
How do you create the stream? The mentioned exception can occur if you don't set the stream position back to zero when feeding it to your Minio client.


`
using (var stream = new MemoryStream())
{
	await file.CopyToAsync(stream);
	stream.Position = 0;

	PutObjectArgs args = new PutObjectArgs()
		.WithBucket(buckName)
		.WithObject(objectName)
		.WithStreamData(stream)
		.WithObjectSize(stream.Length);

	await client.PutObjectAsync(args);
}
`

**Comment by hvppy** [comment] 2022-08-18 01:00
> How do you create the stream? The mentioned exception can occur if you don't set the stream position back to zero when feeding it to your Minio client.
> 
> ```
> using (var stream = new MemoryStream())
> {
> 	await file.CopyToAsync(stream);
> 	stream.Position = 0;
> 
> 	PutObjectArgs args = new PutObjectArgs()
> 		.WithBucket(buckName)
> 		.WithObject(objectName)
> 		.WithStreamData(stream)
> 		.WithObjectSize(stream.Length);
> 
> 	await client.PutObjectAsync(args);
> }
> ```
It's my own problem, which has been solved. Because of the position of stream, stream. Position = 0 is OK

**Comment by ebozduman** [comment] 2022-11-02 02:07
@vuhuy,
Thanks for the suggestion.


@hvppy,
I am not sure if the issue is  resolved for you permanently after @vuhuy's suggestion, as it is still open.

So, before closing the issue, I gave it a try to make sure all is good.
With the latest code from the top of the tree, everything works as expected and I don't see any issues.

I'll close the issue at this point, as both scenarios you've provided above work perfectly fine.
Please reopen the issue, if you can still reproduce it with the latest, and don't forget to add the repro steps.

**Closed by ebozduman** 2022-11-02 02:07 UTC
Labels: working as intended
