### ISSUE TITLE
PutObjectAsync - The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by tinohager** [minio/minio-dotnet#305] opened 2019-05-09 14:29 UTC
PutObjectAsync throw a error with files bigger as 5MB. If i remove some lines from my test file it works!
If i upload the same file via the webinterface MinIO Browser it also works fine.

[test1.txt](https://github.com/minio/minio-dotnet/files/3162601/test1.txt)
[minioclient.log](https://github.com/minio/minio-dotnet/files/3162599/minioclient.log)

```cs
this._minioClient.PutObjectAsync("session", "test.mp4", "test1.txt").GetAwaiter().GetResult();
```

**Comment by tinohager** [comment] 2019-05-09 14:47
If i upload the same file via the webinterface `MinIO Browser` it works fine.

**Comment by tinohager** [comment] 2019-05-09 15:06
I have uninstall the nuget package and reinstall it, now it works. It must be related to the current packages.

![image](https://user-images.githubusercontent.com/8215186/57464293-bb931300-727c-11e9-9f4d-3a598c0badd8.png)

**Comment by kannappanr** [comment] 2019-05-09 15:29
@tinohager Closing this as working as intended.

**Closed by kannappanr** 2019-05-09 15:29 UTC
