### ISSUE TITLE
Could not create SSL/TLS secure channel. 

### ISSUE THREAD

**Issue by justin-oj-orange** [minio/minio-dotnet#258] opened 2018-11-13 22:38 UTC
Just download the Minio .NET SDK Nuget Package, and started with the Play site and the samples verbatim but got the following error on attempt Client connection:

**Minio API responded with message=Unsuccessful response from server without XML error: The request was aborted: Could not create SSL/TLS secure channel.**

Internally we have come across this kinda of error before and it relates to .NET Framework 4.6 upgrade, and this [article](https://support.microsoft.com/en-us/help/3069494/cannot-connect-to-a-server-by-using-the-servicepointmanager-or-sslstre)

The play site (https://play.minio.io:9000) as far as I can tell is using TLS1.2. I have a suspicion that the underlying object that minio sdk is using is still  < 4.6 so TLS 1.2 support not added.

adding the following code (specifically adding TLS1.2 support) before the client request solves the issue, but consider it a work around

 **System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls | System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;**

SDK code may need to add TLS1.2 (debatable?!) protocol (the code may be using the older HttpWebRequest object, which potentially should be using the newer HttpClient object). 

Actually looking at the code, this may be more related to RestSharp... but for those like me trying to get going, this knowledge may be of value....

as per [here](https://stackoverflow.com/questions/52733988/restsharp-request-aborted-could-not-create-ssl-tls-secure-channel) , and the topic as related to Microsoft and the Frameworks [here](https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5)

**Comment by poornas** [comment] 2018-11-13 23:29
@justin-oj-orange, which version of .NET framework are you using? The latest minio .NET SDK version is 2.0.6. Is that what you are using?

**Comment by justin-oj-orange** [comment] 2018-11-14 00:01
@poornas Minio NUGET package was 2.0.6, using .NET Framework 4.6

**Comment by poornas** [comment] 2018-11-14 20:53
@justin-oj-orange, Restsharp sdk uses HttpWebRequest  internally, which might be causing the issue. At present, the work-around would be to set ```System.Net.ServicePointManager.SecurityProtocol```.

**Comment by justin-oj-orange** [comment] 2018-11-14 21:11
@poornas Doing a bit more research, this may purely be inconsistent .NET framework across dependencies. So the minio package 2.0.6 is .NET 4.6< , which is good, but its dependency of RestSharp, (min version 106.3.1), this version looks to be .NET 4.5.2 (that's the dll that's included). so the TLS1.2 is not added as default (it of course is supported just not default) .NET 4.6 its added as default, so you don't need to do anything. It may be simply ensuring that the minio 4.6 package has a dependency on the RestSharp package that is also .NET 4.6. I tried to upgrade the RestSharp library directly (current version is 106.5.4) but appears to be a breaking change in the minio package (ctor issue I do believe)

**Comment by poornas** [comment] 2018-11-14 22:00
Restsharp [Readme](https://github.com/restsharp/RestSharp) still shows .NET 4.5.2

**Comment by deekoder** [comment] 2018-11-29 20:00
Closing this as a working as intended. Please use workaround until further support is available from RestSharp/TLS offers these features.

**Closed by deekoder** 2018-11-29 20:00 UTC
Labels: community, priority: medium, triage
